import { useEffect, useMemo, useRef, useState } from "react";

import {
  buildDiff,
  extractActionsFromText,
  fallbackActions,
  permissionForAction,
  redactSecrets,
  runAutonomousLoop,
  type AgentAction,
  type PermissionRequirement
} from "@lumen/core-agent";
import { Button } from "@/components/ui/button";
import { Modal } from "@/components/ui/modal";
import { Textarea } from "@/components/ui/textarea";
import { createTimelineEntry, timelineFromAudit } from "@/lib/timeline";
import { useAppStore } from "@/state/useAppStore";

type AgentPanelProps = {
  refreshTree: () => Promise<void>;
  openFile: (path: string) => Promise<void>;
};

type ChatLine = {
  id: string;
  role: "user" | "assistant" | "system";
  text: string;
  meta?: {
    reasoning?: ReasoningLevel;
    model?: string;
  };
};

type ApprovalRequest = {
  action: AgentAction;
  requirement: PermissionRequirement;
};

type ReasoningLevel = "low" | "medium" | "high" | "extra_high";

type RelatedFileContext = {
  path: string;
  content: string;
};

type DirectEditResult = {
  pendingChange: {
    id: string;
    type: "write";
    path: string;
    previousContent: string;
    nextContent: string;
    diff: string;
  };
  summary: string;
  relatedPaths: string[];
};

function makeId() {
  return `${Date.now()}-${Math.floor(Math.random() * 10000)}`;
}

function fileLabel(inputPath: string) {
  return inputPath.split(/[\\/]/).filter(Boolean).at(-1) || inputPath;
}

function normalizePath(root: string, inputPath?: string) {
  if (!inputPath || inputPath === ".") return root;
  if (/^[A-Za-z]:\\/.test(inputPath) || inputPath.startsWith("/")) return inputPath;
  return `${root.replace(/[\\/]+$/, "")}\\${inputPath.replace(/^[\\/]+/, "")}`;
}

function extractPathFromPrompt(goal: string) {
  const quotedMatch = goal.match(/["']([^"']+\.[A-Za-z0-9]{1,8})["']/);
  if (quotedMatch?.[1]) return quotedMatch[1];

  const pathMatch = goal.match(/([A-Za-z]:\\[^\s"'`]+|(?:[A-Za-z0-9_.-]+[\\/])*[A-Za-z0-9_.-]+\.[A-Za-z0-9]{1,8})/);
  return pathMatch?.[1] || "";
}

function isEditIntent(goal: string) {
  return /\b(edit|change|modify|update|fix|rewrite|refactor|improve|patch|add|remove|replace|rename|implement|convert|optimize|clean up)\b/i.test(goal);
}

function isReadIntent(goal: string) {
  return /\b(read|open|show|inspect|explain|review|check)\b/i.test(goal);
}

function isBuildIntent(goal: string) {
  return (
    /\b(build|create|make|generate|scaffold|develop)\b/i.test(goal) &&
    /\b(app|application|website|site|landing|dashboard|frontend|ui|web)\b/i.test(goal)
  );
}

function isPreviewIntent(goal: string) {
  return /\b(preview|run|start|launch|open|test)\b/i.test(goal) && /\b(app|project|preview|site|website|ui)\b/i.test(goal);
}

function hasBuildOutputActions(actions: AgentAction[]) {
  return actions.some((action) => action.type === "write_file" || action.type === "delete_file" || action.type === "run_cmd");
}

function sanitizeSegment(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
}

function inferScaffoldFolder(goal: string) {
  const named = goal.match(/\b(?:named|called)\s+["']?([A-Za-z0-9 _-]{2,40})["']?/i)?.[1];
  const segment = sanitizeSegment(named || "");
  if (segment) return segment;
  if (/\bwebsite|site|landing|web\b/i.test(goal)) return "lumen-website";
  return "lumen-app";
}

function defaultScaffoldActions(goal: string): AgentAction[] {
  const folder = inferScaffoldFolder(goal);
  const title = goal.trim().replace(/\s+/g, " ").slice(0, 60) || "Lumen App";

  const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
    <link rel="stylesheet" href="./styles.css" />
  </head>
  <body>
    <main class="app">
      <header class="top">
        <h1>${title}</h1>
        <p>Generated by Lumen IDE agent.</p>
      </header>
      <section class="card">
        <h2>Starter App</h2>
        <p>This offline starter is ready for edits.</p>
        <button id="ping">Test Interaction</button>
        <pre id="output">Click the button to test app.js</pre>
      </section>
    </main>
    <script src="./app.js"></script>
  </body>
</html>
`;

  const css = `:root {
  --bg: #020817;
  --panel: #0b1220;
  --line: #1f2a44;
  --text: #e2e8f0;
  --muted: #94a3b8;
  --accent: #22d3ee;
}

* { box-sizing: border-box; }
body {
  margin: 0;
  font-family: "Segoe UI", Tahoma, sans-serif;
  background: radial-gradient(1200px 600px at 20% -20%, #0f172a, var(--bg));
  color: var(--text);
}
.app {
  max-width: 960px;
  margin: 0 auto;
  padding: 24px;
}
.top h1 {
  margin: 0 0 8px;
  font-size: 1.7rem;
}
.top p {
  margin: 0 0 18px;
  color: var(--muted);
}
.card {
  background: linear-gradient(180deg, rgba(11, 18, 32, 0.95), rgba(11, 18, 32, 0.85));
  border: 1px solid var(--line);
  border-radius: 12px;
  padding: 18px;
}
button {
  border: 1px solid #1e3a8a;
  background: #0f172a;
  color: var(--text);
  border-radius: 8px;
  padding: 8px 12px;
  cursor: pointer;
}
button:hover { border-color: var(--accent); }
pre {
  margin: 12px 0 0;
  padding: 10px;
  border-radius: 8px;
  border: 1px solid var(--line);
  background: rgba(2, 6, 23, 0.7);
  white-space: pre-wrap;
}
`;

  const js = `const button = document.getElementById("ping");
const output = document.getElementById("output");

if (button && output) {
  button.addEventListener("click", () => {
    output.textContent = "App is running. Next step: ask Lumen agent for feature changes.";
  });
}
`;

  const readme = `# ${folder}

Generated by Lumen IDE agent for request:
${goal}

## Run
Open \`index.html\` in a browser.

## Files
- \`index.html\`
- \`styles.css\`
- \`app.js\`
`;

  return [
    { type: "write_file", path: `${folder}/index.html`, content: html, reason: "Create starter website shell" },
    { type: "write_file", path: `${folder}/styles.css`, content: css, reason: "Create starter styles" },
    { type: "write_file", path: `${folder}/app.js`, content: js, reason: "Create starter logic" },
    { type: "write_file", path: `${folder}/README.md`, content: readme, reason: "Create usage notes" }
  ];
}

function reasoningTemperature(level: ReasoningLevel) {
  if (level === "low") return 0.05;
  if (level === "medium") return 0.2;
  if (level === "high") return 0.35;
  return 0.5;
}

function reasoningInstruction(level: ReasoningLevel) {
  if (level === "low") return "Use minimal reasoning and provide a direct, concise result.";
  if (level === "medium") return "Use balanced reasoning and keep the response concise.";
  if (level === "high") return "Use deeper reasoning and verify assumptions before concluding.";
  return "Use maximum careful reasoning and provide the most robust solution with checks.";
}

function maxPlannerActions(level: ReasoningLevel) {
  if (level === "low") return 2;
  if (level === "medium") return 4;
  if (level === "high") return 8;
  return 12;
}

function shouldRunVerify(level: ReasoningLevel, goal: string, pendingChanges: number) {
  const explicitVerify = /\b(test|lint|verify|check|build|compile)\b/i.test(goal);
  const heavierEdit = /\b(refactor|rewrite|migrate|convert)\b/i.test(goal);
  if (level === "low") return false;
  if (level === "medium") return explicitVerify;
  if (level === "high") return explicitVerify || (pendingChanges > 0 && heavierEdit);
  return pendingChanges > 0 || explicitVerify;
}

function stringifyOutput(value: unknown) {
  if (typeof value === "string") return value;
  try {
    return JSON.stringify(value, null, 2);
  } catch {
    return String(value);
  }
}

function parseRelativeSpecifiers(source: string) {
  const specifiers = new Set<string>();
  const patterns = [
    /(?:import|export)\s+[^"'`]*?\sfrom\s+["']([^"']+)["']/g,
    /import\s*\(\s*["']([^"']+)["']\s*\)/g,
    /require\(\s*["']([^"']+)["']\s*\)/g
  ];

  for (const pattern of patterns) {
    let match = pattern.exec(source);
    while (match) {
      const specifier = match[1]?.trim();
      if (specifier?.startsWith(".")) {
        specifiers.add(specifier);
      }
      match = pattern.exec(source);
    }
  }

  return Array.from(specifiers);
}

function resolveLocalCandidatePaths(targetPath: string, specifier: string) {
  const normalizedBase = normalizePath(targetPath.replace(/[\\/][^\\/]+$/, ""), specifier).replace(/\//g, "\\");
  const candidates = new Set<string>();
  const extensions = ["", ".ts", ".tsx", ".js", ".jsx", ".css", ".json", ".md", "\\index.ts", "\\index.tsx", "\\index.js"];

  for (const extension of extensions) {
    candidates.add(`${normalizedBase}${extension}`);
  }

  return Array.from(candidates);
}

function buildFastSummary(
  goal: string,
  actions: AgentAction[],
  actionResults: Array<{ action: AgentAction; result: { ok: boolean; output?: unknown; error?: string }; skipped?: boolean }>,
  pendingCount: number,
  verifyResult: { ok: boolean; output?: unknown; error?: string } | null,
  extra?: string
) {
  const completed = actionResults.filter((item) => item.result.ok && !item.skipped).length;
  const firstChange = actionResults.find((item) => item.action.path)?.action.path;
  const targetText = firstChange ? ` Target: ${fileLabel(firstChange)}.` : "";
  const verifyText = verifyResult ? ` Verify: ${verifyResult.ok ? "pass" : "fail"}.` : "";
  const extraText = extra ? ` ${extra}` : "";
  return `Ran ${completed}/${actions.length} actions for "${goal}". Pending changes: ${pendingCount}.${targetText}${verifyText}${extraText}`.trim();
}

export function AgentPanel({ refreshTree, openFile }: AgentPanelProps) {
  const workspaceRoot = useAppStore((state) => state.workspaceRoot);
  const settings = useAppStore((state) => state.settings);
  const tabs = useAppStore((state) => state.tabs);
  const activeTabId = useAppStore((state) => state.activeTabId);
  const terminalTabs = useAppStore((state) => state.terminalTabs);
  const terminalVisible = useAppStore((state) => state.terminalVisible);
  const addTerminalTab = useAppStore((state) => state.addTerminalTab);
  const setActiveTerminal = useAppStore((state) => state.setActiveTerminal);
  const toggleTerminal = useAppStore((state) => state.toggleTerminal);
  const setRightPanelTab = useAppStore((state) => state.setRightPanelTab);
  const appendAudit = useAppStore((state) => state.appendAudit);
  const appendTimeline = useAppStore((state) => state.appendTimeline);
  const pendingChanges = useAppStore((state) => state.pendingChanges);
  const setPendingChanges = useAppStore((state) => state.setPendingChanges);
  const clearPendingChanges = useAppStore((state) => state.clearPendingChanges);
  const patchSessionMemory = useAppStore((state) => state.patchSessionMemory);

  const [prompt, setPrompt] = useState("");
  const [messages, setMessages] = useState<ChatLine[]>([]);
  const [planLines, setPlanLines] = useState<string[]>([]);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [streamStatus, setStreamStatus] = useState("");
  const [approval, setApproval] = useState<ApprovalRequest | null>(null);
  const [chatModel, setChatModel] = useState(settings.model);
  const [reasoningLevel, setReasoningLevel] = useState<ReasoningLevel>("medium");
  const [fullAccessMode, setFullAccessMode] = useState(true);
  const [showPlan, setShowPlan] = useState(false);

  const promptInputRef = useRef<HTMLTextAreaElement | null>(null);
  const resolveApprovalRef = useRef<((approved: boolean) => void) | null>(null);

  useEffect(() => {
    setChatModel((current) => current || settings.model);
  }, [settings.model]);

  const activeTabPath = useMemo(() => tabs.find((tab) => tab.id === activeTabId)?.path || "", [tabs, activeTabId]);
  const helperConnection = useMemo(
    () =>
      settings.helperEnabled
        ? {
            baseUrl: (settings.helperUsesMainConnection ? settings.baseUrl : settings.helperBaseUrl).trim(),
            model: settings.helperModel.trim(),
            apiKey: settings.helperUsesMainConnection ? settings.apiKey : settings.helperApiKey
          }
        : null,
    [
      settings.apiKey,
      settings.baseUrl,
      settings.helperApiKey,
      settings.helperBaseUrl,
      settings.helperEnabled,
      settings.helperModel,
      settings.helperUsesMainConnection
    ]
  );

  const pushMessage = (role: ChatLine["role"], text: string, meta?: ChatLine["meta"]) => {
    setMessages((prev) => [...prev, { id: makeId(), role, text, meta }]);
  };

  const recordAudit = (entry: Parameters<typeof appendAudit>[0]) => {
    appendAudit(entry);
    const timelineEntry = timelineFromAudit(entry);
    if (timelineEntry) {
      appendTimeline(timelineEntry);
    }
  };

  const shouldMirrorLoopAudit = (action: string) =>
    ![
      "agent.run_cmd",
      "agent.preview_start",
      "agent.preview_status",
      "agent.preview_snapshot",
      "agent.preview_click",
      "agent.preview_type",
      "agent.preview_press",
      "agent.git_status",
      "agent.git_diff",
      "agent.git_stage",
      "agent.git_unstage",
      "agent.git_commit",
      "agent.git_push"
    ].includes(action);

  const ensureNamedTerminal = async (title: string) => {
    const existing = terminalTabs.find((tab) => tab.title === title);
    if (existing) {
      setActiveTerminal(existing.id);
      if (!terminalVisible) toggleTerminal();
      return existing.id;
    }

    const created = await window.lumen.terminal.create({ cols: 120, rows: 30 });
    addTerminalTab({ id: created.id, title });
    setActiveTerminal(created.id);
    if (!terminalVisible) toggleTerminal();
    return created.id;
  };

  const requestApproval = async (action: AgentAction, requirement: PermissionRequirement) => {
    if (fullAccessMode) return true;
    return await new Promise<boolean>((resolve) => {
      resolveApprovalRef.current = resolve;
      setApproval({ action, requirement });
    });
  };

  const streamToText = async (
    modelMessages: Array<{ role: "system" | "user" | "assistant"; content: string }>,
    options?: { includeReasoning?: boolean; statusLabel?: string; modelRole?: "main" | "helper" }
  ) => {
    const requestId = makeId();
    const modelRole = options?.modelRole || "main";
    const modelConfig =
      modelRole === "helper" && helperConnection?.baseUrl && helperConnection?.model
        ? helperConnection
        : {
            baseUrl: settings.baseUrl,
            model: chatModel.trim() || settings.model,
            apiKey: settings.apiKey
          };
    const chosenModel = modelConfig.model;
    const includeReasoning = options?.includeReasoning !== false;
    const enhancedMessages = includeReasoning
      ? [{ role: "system" as const, content: `Reasoning mode: ${reasoningInstruction(reasoningLevel)}` }, ...modelMessages]
      : modelMessages;

    return await new Promise<string>((resolve, reject) => {
      let full = "";
      setStreamStatus(options?.statusLabel || `Contacting ${modelRole === "helper" ? "helper" : "main"} model: ${chosenModel}`);

      const offChunk = window.lumen.llm.onChunk(({ requestId: chunkId, delta }) => {
        if (chunkId !== requestId) return;
        full += delta;
      });
      const offStatus = window.lumen.llm.onStatus(({ requestId: statusId, message }) => {
        if (statusId !== requestId) return;
        setStreamStatus(message || "Streaming response...");
      });
      const offDone = window.lumen.llm.onDone(({ requestId: doneId }) => {
        if (doneId !== requestId) return;
        offChunk();
        offStatus();
        offDone();
        offError();
        setStreamStatus("");
        resolve(full);
      });
      const offError = window.lumen.llm.onError(({ requestId: errorId, error: streamError }) => {
        if (errorId !== requestId) return;
        offChunk();
        offStatus();
        offDone();
        offError();
        setStreamStatus("");
        reject(new Error(streamError));
      });

      void window.lumen.llm
        .startStream({
          requestId,
          config: {
            baseUrl: modelConfig.baseUrl,
            model: chosenModel,
            apiKey: modelConfig.apiKey,
            temperature: reasoningTemperature(reasoningLevel)
          },
          messages: enhancedMessages
        })
        .catch((nextError) => {
          offChunk();
          offStatus();
          offDone();
          offError();
          setStreamStatus("");
          reject(nextError instanceof Error ? nextError : new Error("Failed to start stream"));
        });
    });
  };

  const resolveTargetPath = (goal: string) => {
    const fromPrompt = extractPathFromPrompt(goal);
    if (fromPrompt) return normalizePath(workspaceRoot, fromPrompt);
    if (activeTabPath) return activeTabPath;
    return "";
  };

  const gatherRelatedContext = async (targetPath: string, source: string) => {
    const candidatePaths = new Set<string>();
    for (const specifier of parseRelativeSpecifiers(source)) {
      for (const candidate of resolveLocalCandidatePaths(targetPath, specifier)) {
        candidatePaths.add(candidate);
      }
    }

    const siblingBase = targetPath.replace(/\.[^.]+$/, "");
    [`${siblingBase}.css`, `${siblingBase}.module.css`, `${siblingBase}.json`].forEach((candidate) => candidatePaths.add(candidate));

    const related: RelatedFileContext[] = [];
    for (const candidate of Array.from(candidatePaths)) {
      if (candidate === targetPath || related.length >= 3) continue;
      try {
        const file = await window.lumen.workspace.read({ path: candidate });
        if (!file.content.trim()) continue;
        related.push({
          path: file.path,
          content: file.content.slice(0, 12000)
        });
      } catch {
        // Ignore missing or unreadable neighbor files.
      }
    }

    return related;
  };

  const shouldUseDirectEditPath = (goal: string) => {
    if (isBuildIntent(goal) || !isEditIntent(goal)) return false;
    return Boolean(resolveTargetPath(goal));
  };

  const heuristicActions = (goal: string): AgentAction[] => {
    const actions: AgentAction[] = [];
    const targetPath = resolveTargetPath(goal);

    if (isBuildIntent(goal)) {
      return defaultScaffoldActions(goal);
    }

    if (isPreviewIntent(goal)) {
      return [
        { type: "preview_start", path: ".", reason: "Run the current project preview inside the workspace" },
        { type: "preview_snapshot", reason: "Inspect the running preview" }
      ];
    }

    if (isReadIntent(goal) && targetPath) {
      actions.push({ type: "read_file", path: targetPath, reason: "Read target file from prompt/active tab" });
    }

    if (isEditIntent(goal) && targetPath) {
      actions.push({ type: "read_file", path: targetPath, reason: "Load file before edit proposal" });
    }

    if (actions.length > 0) return actions;
    return fallbackActions(goal);
  };

  const buildScaffoldActions = async (goal: string): Promise<AgentAction[]> => {
    const fallback = defaultScaffoldActions(goal);
    const prompt = [
      "Return only a JSON array.",
      "Schema:",
      '[{"path":"relative/path.ext","content":"full file content"}]',
      "Generate a complete starter app that is runnable offline.",
      "Keep to 3-8 files.",
      "No markdown fences.",
      "No prose outside JSON."
    ].join("\n");

    try {
      const text = await streamToText([
        { role: "system", content: prompt },
        { role: "user", content: `Build this app or website:\n${goal}` }
      ]);
      const cleaned = text.trim().replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "");
      const parsed = JSON.parse(cleaned);
      if (!Array.isArray(parsed)) return fallback;

      const generated = parsed
        .filter((item): item is { path: string; content: string } => {
          if (!item || typeof item !== "object") return false;
          const candidate = item as Record<string, unknown>;
          return typeof candidate.path === "string" && typeof candidate.content === "string";
        })
        .map((item) => ({
          type: "write_file" as const,
          path: item.path.replace(/\\/g, "/").replace(/^\/+/, ""),
          content: item.content,
          reason: "Scaffold project file"
        }))
        .filter((item) => item.path.length > 0 && !item.path.includes(".."));

      return generated.length ? generated : fallback;
    } catch {
      return fallback;
    }
  };

  const proposeDirectEdit = async (goal: string): Promise<DirectEditResult | null> => {
    const targetPath = resolveTargetPath(goal);
    if (!targetPath || !isEditIntent(goal)) return null;

    let before = "";
    try {
      before = (await window.lumen.workspace.read({ path: targetPath })).content;
    } catch {
      before = "";
    }

    if (before.length > 180000) {
      throw new Error("Active file is too large for direct edit fallback. Open a smaller file or specify targeted edits.");
    }

    const relatedContext = before ? await gatherRelatedContext(targetPath, before) : [];

    const systemPrompt = [
      "You are Lumen IDE fast edit mode.",
      reasoningInstruction(reasoningLevel),
      "Return only JSON with keys summary and content.",
      'Schema: {"summary":"short user-facing summary","content":"full updated file content"}',
      "Make the smallest correct edit that satisfies the request.",
      "Preserve unrelated code, imports, formatting style, and working behavior.",
      "Do not include markdown fences or extra prose."
    ].join("\n");

    const text = await streamToText([
      { role: "system", content: systemPrompt },
      {
        role: "user",
        content: [
          `User request:\n${goal}`,
          `Target file:\n${targetPath}`,
          before ? `Current file content:\n${before}` : "Current file content:\n<file does not exist yet>",
          relatedContext.length
            ? `Related workspace context:\n${relatedContext
                .map((item) => `FILE: ${item.path}\n${item.content}`)
                .join("\n\n")}`
            : ""
        ]
          .filter(Boolean)
          .join("\n\n")
      }
    ], { statusLabel: `Editing ${fileLabel(targetPath)}...` });

    const cleaned = text.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "").trim();
    let nextContent = "";
    let summary = "";

    try {
      const parsed = JSON.parse(cleaned) as { summary?: string; content?: string };
      nextContent = String(parsed.content || "").trimEnd();
      summary = String(parsed.summary || "").trim();
    } catch {
      nextContent = cleaned.trimEnd();
    }

    if (!nextContent || nextContent === before) return null;

    return {
      pendingChange: {
        id: makeId(),
        type: "write" as const,
        path: targetPath,
        previousContent: before,
        nextContent,
        diff: buildDiff(targetPath, before, nextContent)
      },
      summary: summary || `Prepared edits for ${fileLabel(targetPath)}.`,
      relatedPaths: relatedContext.map((item) => item.path)
    };
  };

  const planActions = async (goal: string): Promise<AgentAction[]> => {
    const systemPrompt = [
      "You are Lumen IDE autonomous planner.",
      "Return only JSON array. No prose.",
      `Reasoning level: ${reasoningLevel}`,
      reasoningInstruction(reasoningLevel),
      `Prefer no more than ${maxPlannerActions(reasoningLevel)} actions unless strictly needed.`,
      "Allowed action types:",
      "list_dir, read_file, search_files, write_file, delete_file, run_cmd, preview_start, preview_status, preview_snapshot, preview_click, preview_type, preview_press, git_status, git_diff, git_stage, git_unstage, git_commit, git_push",
      "For write_file include path and full desired content.",
      "Use preview_start to run the current project or a static workspace folder in Lumen preview.",
      "Use preview_snapshot after preview_start to inspect the page text/title.",
      "Use preview_click and preview_type with CSS selectors.",
      "Do not use remote actions."
    ].join("\n");

    try {
      const text = await streamToText([
        { role: "system", content: systemPrompt },
        { role: "user", content: goal }
      ], {
        statusLabel: helperConnection?.model ? `Planning with helper model: ${helperConnection.model}` : "Planning actions...",
        modelRole: "helper"
      });
      const actions = extractActionsFromText(text).slice(0, maxPlannerActions(reasoningLevel));
      if (actions.length === 0) {
        return heuristicActions(goal);
      }
      if (isBuildIntent(goal) && !hasBuildOutputActions(actions)) {
        return await buildScaffoldActions(goal);
      }
      return actions;
    } catch {
      const fallback = heuristicActions(goal);
      if (isBuildIntent(goal) && !hasBuildOutputActions(fallback)) {
        return await buildScaffoldActions(goal);
      }
      return fallback;
    }
  };

  const executeAction = async (action: AgentAction) => {
    switch (action.type) {
      case "list_dir": {
        const listed = await window.lumen.workspace.list({ path: normalizePath(workspaceRoot, action.path) });
        return { ok: true, output: listed.tree };
      }
      case "read_file": {
        const read = await window.lumen.workspace.read({ path: normalizePath(workspaceRoot, action.path) });
        return { ok: true, output: read.content };
      }
      case "search_files": {
        const result = await window.lumen.workspace.search({ query: action.query || "", maxResults: 80 });
        return { ok: true, output: result.results };
      }
      case "write_file": {
        const targetPath = normalizePath(workspaceRoot, action.path);
        let before = "";
        try {
          before = (await window.lumen.workspace.read({ path: targetPath })).content;
        } catch {
          before = "";
        }
        const next = action.content || "";
        const diff = buildDiff(targetPath, before, next);

        return {
          ok: true,
          output: "pending write",
          pendingChange: {
            id: makeId(),
            type: "write" as const,
            path: targetPath,
            previousContent: before,
            nextContent: next,
            diff
          }
        };
      }
      case "delete_file": {
        const targetPath = normalizePath(workspaceRoot, action.path);
        const before = (await window.lumen.workspace.read({ path: targetPath })).content;
        const diff = buildDiff(targetPath, before, "");
        return {
          ok: true,
          output: "pending delete",
          pendingChange: {
            id: makeId(),
            type: "delete" as const,
            path: targetPath,
            previousContent: before,
            nextContent: "",
            diff
          }
        };
      }
      case "run_cmd": {
        const terminalId = await ensureNamedTerminal("Agent");
        const result = await window.lumen.agent.runCmd({ command: action.command || "", terminalId });
        if (result.code !== 0) {
          patchSessionMemory({
            lastFailedCommand: action.command || "",
            knownBlockers: [result.stderr || result.stdout || "Command failed"]
          });
        }
        return { ok: result.code === 0, output: `${result.stdout}\n${result.stderr}`.trim() };
      }
      case "preview_start": {
        setRightPanelTab("preview");
        const terminalId = await ensureNamedTerminal("Preview");
        try {
          const result = await window.lumen.preview.startProject({
            path: action.path || ".",
            command: action.command,
            url: action.url,
            port: action.port,
            terminalId
          });
          patchSessionMemory({
            activePreviewUrl: result.url,
            previewMode: result.mode
          });
          return { ok: true, output: result };
        } catch {
          const result = await window.lumen.preview.start({
            path: action.path || ".",
            entry: action.entry || "index.html",
            port: action.port
          });
          patchSessionMemory({
            activePreviewUrl: result.url,
            previewMode: result.mode
          });
          return { ok: true, output: result };
        }
      }
      case "preview_status": {
        const result = await window.lumen.preview.status();
        return { ok: true, output: result };
      }
      case "preview_snapshot": {
        const status = await window.lumen.preview.status();
        const result = status.browser.connected
          ? await window.lumen.preview.browserSnapshot()
          : (await window.lumen.preview.browserConnect({ url: action.url || status.url })).snapshot;
        return { ok: true, output: result };
      }
      case "preview_click": {
        const status = await window.lumen.preview.status();
        if (!status.browser.connected) {
          await window.lumen.preview.browserConnect({ url: action.url || status.url });
        }
        const result = await window.lumen.preview.browserClick({ selector: action.selector || "", url: action.url });
        return { ok: true, output: result };
      }
      case "preview_type": {
        const status = await window.lumen.preview.status();
        if (!status.browser.connected) {
          await window.lumen.preview.browserConnect({ url: action.url || status.url });
        }
        const result = await window.lumen.preview.browserType({
          selector: action.selector || "",
          text: action.text || "",
          url: action.url
        });
        return { ok: true, output: result };
      }
      case "preview_press": {
        const status = await window.lumen.preview.status();
        if (!status.browser.connected) {
          await window.lumen.preview.browserConnect({ url: action.url || status.url });
        }
        const result = await window.lumen.preview.browserPress({ key: action.key || "Enter", url: action.url });
        return { ok: true, output: result };
      }
      case "git_status": {
        const result = await window.lumen.git.status();
        return { ok: true, output: result };
      }
      case "git_diff": {
        const result = await window.lumen.git.diff({ path: action.path, staged: action.staged });
        return { ok: true, output: result.diff };
      }
      case "git_stage": {
        await window.lumen.git.stage({ paths: action.paths || (action.path ? [action.path] : []) });
        return { ok: true, output: "staged" };
      }
      case "git_unstage": {
        await window.lumen.git.unstage({ paths: action.paths || (action.path ? [action.path] : []) });
        return { ok: true, output: "unstaged" };
      }
      case "git_commit": {
        const result = await window.lumen.git.commit({ message: action.message || "Lumen IDE commit" });
        return { ok: true, output: result.hash };
      }
      case "git_push": {
        await window.lumen.git.push();
        return { ok: true, output: "pushed" };
      }
      default:
        return { ok: false, error: "Unsupported action" };
    }
  };

  const runAgent = async () => {
    const goal = prompt.trim();
    if (!goal || busy) return;

    setBusy(true);
    setError("");
    pushMessage("user", goal);
    setPrompt("");
    patchSessionMemory({
      currentGoal: goal,
      verificationStatus: "idle",
      knownBlockers: [],
      lastFailedCommand: "",
      filesTouched: []
    });
    appendTimeline(
      createTimelineEntry({
        phase: "understand",
        status: "running",
        title: "Goal received",
        detail: goal,
        source: "agent"
      })
    );

    try {
      if (shouldUseDirectEditPath(goal)) {
        const fastEdit = await proposeDirectEdit(goal);
        if (fastEdit) {
          const pendingList = [
            {
              id: fastEdit.pendingChange.id,
              path: fastEdit.pendingChange.path,
              type: fastEdit.pendingChange.type,
              diff: fastEdit.pendingChange.diff,
              nextContent: fastEdit.pendingChange.nextContent
            }
          ];
          const directAction: AgentAction = {
            type: "write_file",
            path: fastEdit.pendingChange.path,
            reason: "Fast direct edit path"
          };

          setPlanLines([
            `FAST EDIT: ${fileLabel(fastEdit.pendingChange.path)}`,
            "CONTEXT: use active file and nearby imports",
            "PROPOSE: generate one pending diff immediately",
            "APPLY: only after explicit approval"
          ]);
          setPendingChanges(pendingList);
          recordAudit({
            id: makeId(),
            timestamp: new Date().toISOString(),
            action: "agent.fast_edit",
            detail: {
              path: fastEdit.pendingChange.path,
              relatedFiles: fastEdit.relatedPaths
            }
          });
          patchSessionMemory({
            filesTouched: [fastEdit.pendingChange.path],
            verificationStatus: shouldRunVerify(reasoningLevel, goal, pendingList.length) ? "pending" : "skipped"
          });

          let verifyResult: { ok: boolean; output?: unknown; error?: string } | null = null;
          const shouldVerify = shouldRunVerify(reasoningLevel, goal, pendingList.length);
          if (shouldVerify) {
            const verifyAction: AgentAction = {
              type: "run_cmd",
              command: "pnpm test --if-present",
              reason: "VERIFY step after fast edit"
            };
            const verifyRequirement = permissionForAction(verifyAction);
            let verifyApproved = true;
            if (verifyRequirement.approvalRequired) {
              verifyApproved = await requestApproval(verifyAction, verifyRequirement);
            }
            if (verifyApproved) {
              verifyResult = await executeAction(verifyAction);
              recordAudit({
                id: makeId(),
                timestamp: new Date().toISOString(),
                action: "agent.verify",
                detail: { ok: verifyResult.ok, path: fastEdit.pendingChange.path }
              });
              patchSessionMemory({
                verificationStatus: verifyResult.ok ? "passed" : "failed",
                lastFailedCommand: verifyResult.ok ? "" : verifyAction.command || "",
                knownBlockers: verifyResult.ok ? [] : [verifyResult.error || "Verification failed"]
              });
            } else {
              patchSessionMemory({ verificationStatus: "skipped" });
            }
          }

          pushMessage(
            "assistant",
            `${fastEdit.summary}${fastEdit.relatedPaths.length ? ` Context: ${fastEdit.relatedPaths.map(fileLabel).join(", ")}.` : ""}${
              verifyResult ? ` Verify: ${verifyResult.ok ? "pass" : "fail"}.` : ""
            }`,
            {
              reasoning: reasoningLevel,
              model: chatModel.trim() || settings.model
            }
          );
          return;
        }
      }

      let actions = await planActions(goal);

      let loopResult = await runAutonomousLoop({
        goal,
        actions,
        onlineMode: settings.onlineMode,
        executeTool: executeAction,
        requestApproval,
        log: (entry) => {
          if (!shouldMirrorLoopAudit(entry.action)) return;
          recordAudit({
            id: makeId(),
            timestamp: entry.timestamp,
            action: entry.action,
            detail: entry.detail
          });
        }
      });

      if (isBuildIntent(goal) && loopResult.pendingChanges.length === 0) {
        pushMessage("system", "Planner produced no file changes. Switching to scaffold build mode.");
        actions = await buildScaffoldActions(goal);
        loopResult = await runAutonomousLoop({
          goal,
          actions,
          onlineMode: settings.onlineMode,
          executeTool: executeAction,
          requestApproval,
          log: (entry) => {
            if (!shouldMirrorLoopAudit(entry.action)) return;
            recordAudit({
              id: makeId(),
              timestamp: entry.timestamp,
              action: entry.action,
              detail: entry.detail
            });
          }
        });
      }

      let verifyResult = loopResult.verifyResult;
      const shouldVerify = shouldRunVerify(reasoningLevel, goal, loopResult.pendingChanges.length);
      if (shouldVerify) {
        const verifyAction: AgentAction = {
          type: "run_cmd",
          command: "pnpm test --if-present",
          reason: "VERIFY step after proposed changes"
        };
        const verifyRequirement = permissionForAction(verifyAction);
        let verifyApproved = true;
        if (verifyRequirement.approvalRequired) {
          verifyApproved = await requestApproval(verifyAction, verifyRequirement);
        }
        if (verifyApproved) {
          patchSessionMemory({ verificationStatus: "pending" });
          verifyResult = await executeAction(verifyAction);
          recordAudit({
            id: makeId(),
            timestamp: new Date().toISOString(),
            action: "agent.verify",
            detail: { ok: verifyResult.ok }
          });
          patchSessionMemory({
            verificationStatus: verifyResult.ok ? "passed" : "failed",
            lastFailedCommand: verifyResult.ok ? "" : verifyAction.command || "",
            knownBlockers: verifyResult.ok ? [] : [verifyResult.error || "Verification failed"]
          });
        } else {
          verifyResult = { ok: false, error: "Verification command denied by user" };
          patchSessionMemory({
            verificationStatus: "skipped",
            knownBlockers: ["Verification command denied by user"]
          });
        }
      } else {
        patchSessionMemory({ verificationStatus: "skipped" });
      }

      const fallbackEdit = await proposeDirectEdit(goal).catch((fallbackError) => {
        pushMessage("system", fallbackError instanceof Error ? fallbackError.message : "Direct edit fallback failed.");
        return null;
      });
      const allPendingChanges = fallbackEdit
        ? [...loopResult.pendingChanges, fallbackEdit.pendingChange]
        : loopResult.pendingChanges;

      const failedActions = loopResult.actionResults.filter((item) => !item.result.ok && !item.skipped);
      const failedCommand = failedActions.find((item) => item.action.type === "run_cmd")?.action.command || "";
      patchSessionMemory({
        filesTouched: allPendingChanges.map((change) => change.path),
        lastFailedCommand: failedCommand,
        knownBlockers: failedActions.map(
          (item) => item.result.error || item.action.reason || `${item.action.type} failed`
        )
      });

      setPlanLines(loopResult.plan);
      setPendingChanges(
        allPendingChanges.map((change) => ({
          id: change.id,
          path: change.path,
          type: change.type,
          diff: change.diff,
          nextContent: change.nextContent
        }))
      );

      const assistantReply = buildFastSummary(
        goal,
        actions,
        loopResult.actionResults,
        allPendingChanges.length,
        verifyResult
      );

      pushMessage("assistant", assistantReply, {
        reasoning: reasoningLevel,
        model: chatModel.trim() || settings.model
      });
    } catch (nextError) {
      const message = nextError instanceof Error ? nextError.message : "Agent run failed";
      setError(message);
      patchSessionMemory({
        verificationStatus: "failed",
        knownBlockers: [message]
      });
      appendTimeline(
        createTimelineEntry({
          phase: "recover",
          status: "failed",
          title: "Agent run failed",
          detail: message,
          source: "agent"
        })
      );
      pushMessage("system", message);
    } finally {
      setBusy(false);
      setStreamStatus("");
      setTimeout(() => promptInputRef.current?.focus(), 0);
    }
  };

  const applyPendingChanges = async () => {
    if (!pendingChanges.length) return;
    if (!window.confirm(`Apply ${pendingChanges.length} pending change(s)?`)) return;

    const changesToApply = [...pendingChanges];
    for (const change of pendingChanges) {
      if (change.type === "write") {
        await window.lumen.workspace.write({ path: change.path, content: change.nextContent });
      } else {
        await window.lumen.workspace.delete({ path: change.path });
      }
    }

    clearPendingChanges();
    await refreshTree();
    if (changesToApply.length === 1) {
      await openFile(changesToApply[0].path);
    }
    patchSessionMemory({
      filesTouched: changesToApply.map((change) => change.path),
      knownBlockers: []
    });
    appendTimeline(
      createTimelineEntry({
        phase: "apply",
        status: "done",
        title: "Patch applied",
        detail: `${changesToApply.length} file change(s) written to workspace`,
        source: "agent"
      })
    );
    pushMessage("system", "Changes applied.");
  };

  const diffPreview = useMemo(() => pendingChanges.map((change) => change.diff).join("\n"), [pendingChanges]);
  const modelOptions = useMemo(
    () => Array.from(new Set([chatModel, settings.model, ...(settings.recentModels || [])].filter(Boolean))),
    [chatModel, settings.model, settings.recentModels]
  );

  return (
    <div className="flex h-full flex-col">
      <div className="border-b border-border px-3 py-2">
        <div className="mb-1 text-[11px] uppercase tracking-wide text-muted">AI Agent</div>
        <div className="mb-2 text-[11px] text-muted">
          Main: {chatModel.trim() || settings.model}
          {helperConnection?.model ? ` · Helper: ${helperConnection.model}` : ""}
        </div>
        <div className="grid grid-cols-2 gap-2 text-[11px]">
          <label className="block">
            <div className="mb-1 text-muted">Chat Model</div>
            <input
              list="agent-models"
              className="h-8 w-full rounded border border-border bg-black/20 px-2 text-xs"
              value={chatModel}
              onChange={(event) => setChatModel(event.target.value)}
            />
            <datalist id="agent-models">
              {modelOptions.map((model) => (
                <option key={model} value={model} />
              ))}
            </datalist>
          </label>
          <label className="block">
            <div className="mb-1 text-muted">Reasoning</div>
            <select
              className="h-8 w-full rounded border border-border bg-black/20 px-2 text-xs"
              value={reasoningLevel}
              onChange={(event) => setReasoningLevel(event.target.value as ReasoningLevel)}
            >
              <option value="low">Low</option>
              <option value="medium">Medium</option>
              <option value="high">High</option>
              <option value="extra_high">Extra High</option>
            </select>
          </label>
        </div>
        <div className="mt-2 flex items-center gap-3 text-[11px]">
          <label className="flex items-center gap-1.5">
            <input type="checkbox" checked={fullAccessMode} onChange={(event) => setFullAccessMode(event.target.checked)} />
            <span>Full Access Mode (auto-approve)</span>
          </label>
          <label className="flex items-center gap-1.5">
            <input type="checkbox" checked={showPlan} onChange={(event) => setShowPlan(event.target.checked)} />
            <span>Show Plan</span>
          </label>
        </div>
      </div>

      <div className="lumen-scroll flex-1 overflow-auto p-2">
        {messages.length === 0 && (
          <div className="mb-2 rounded border border-border bg-black/20 p-2 text-[11px] text-muted">
            Agent loop: PLAN → EXECUTE → VERIFY → PROPOSE → APPLY
          </div>
        )}
        {messages.map((line) => (
          <div
            key={line.id}
            className={`mb-2 flex ${line.role === "assistant" ? "justify-end" : line.role === "user" ? "justify-start" : "justify-center"}`}
          >
            <div
              className={`max-w-[92%] rounded border p-2 text-[11px] ${
                line.role === "assistant"
                  ? "border-accent/40 bg-accent/5"
                  : line.role === "user"
                    ? "border-border bg-black/20"
                    : "border-border bg-black/25"
              }`}
            >
            <div className="mb-1 flex items-center justify-between gap-2">
              <div className="text-[10px] uppercase text-muted">{line.role}</div>
              {line.role === "assistant" && line.meta && (
                <div className="flex items-center gap-1">
                  {line.meta.reasoning && (
                    <span className="rounded border border-accent/40 bg-accent/10 px-1.5 py-0.5 text-[10px] text-accent">
                      reasoning: {line.meta.reasoning.replace("_", " ")}
                    </span>
                  )}
                  {line.meta.model && (
                    <span className="rounded border border-border px-1.5 py-0.5 text-[10px] text-muted">
                      model: {line.meta.model}
                    </span>
                  )}
                </div>
              )}
            </div>
            <div className="whitespace-pre-wrap break-words">{line.text}</div>
          </div>
          </div>
        ))}

        {showPlan && planLines.length > 0 && (
          <div className="mb-2 rounded border border-border bg-black/20 p-2 text-[11px]">
            <div className="mb-1 text-[10px] uppercase text-muted">Plan</div>
            <ol className="list-decimal pl-4">
              {planLines.map((line) => (
                <li key={line}>{line}</li>
              ))}
            </ol>
          </div>
        )}

        {pendingChanges.length > 0 && (
          <div className="mb-2 rounded border border-accent/40 bg-accent/5 p-2 text-[11px]">
            <div className="mb-2 text-[10px] uppercase text-accent">Proposed Diff Preview</div>
            <pre className="lumen-scroll max-h-56 overflow-auto whitespace-pre-wrap break-words rounded border border-border bg-black/30 p-2">
              {redactSecrets(diffPreview)}
            </pre>
            <div className="mt-2 flex gap-2">
              <Button onClick={() => void applyPendingChanges()}>Apply Changes</Button>
              <Button
                onClick={() => {
                  clearPendingChanges();
                  appendTimeline(
                    createTimelineEntry({
                      phase: "propose",
                      status: "blocked",
                      title: "Patch discarded",
                      detail: "Pending proposal was cleared without apply",
                      source: "agent"
                    })
                  );
                }}
              >
                Discard
              </Button>
            </div>
          </div>
        )}
      </div>

      <div className="space-y-2 border-t border-border p-2">
        <Textarea
          ref={promptInputRef}
          id="agent-prompt"
          value={prompt}
          onChange={(event) => setPrompt(event.target.value)}
          onKeyDown={(event) => {
            if (event.key === "Enter" && event.ctrlKey) {
              event.preventDefault();
              void runAgent();
            }
          }}
          rows={3}
          spellCheck={false}
          placeholder="Enter = new line, Ctrl+Enter = send"
        />
        {streamStatus && <div className="text-[11px] text-muted">{streamStatus}</div>}
        <div className="flex gap-2">
          <Button onClick={() => void runAgent()} disabled={busy || !prompt.trim()}>
            {busy ? "Running..." : "Run Agent"}
          </Button>
          <Button
            onClick={() => {
              setMessages([]);
              setPlanLines([]);
              clearPendingChanges();
            }}
          >
            Clear
          </Button>
        </div>
        {error && <div className="text-[11px] text-bad">{error}</div>}
      </div>

      <Modal
        open={Boolean(approval)}
        title="Permission Required"
        onConfirm={() => {
          resolveApprovalRef.current?.(true);
          resolveApprovalRef.current = null;
          setApproval(null);
        }}
        onCancel={() => {
          resolveApprovalRef.current?.(false);
          resolveApprovalRef.current = null;
          setApproval(null);
        }}
        confirmLabel="Approve Action"
      >
        {approval && (
          <div className="space-y-2">
            <div>
              <span className="text-muted">Action:</span> {approval.action.type}
            </div>
            <div>
              <span className="text-muted">Reason:</span> {approval.requirement.reason}
            </div>
            <pre className="whitespace-pre-wrap break-words rounded border border-border bg-black/30 p-2 text-[11px]">
              {JSON.stringify(approval.action, null, 2)}
            </pre>
          </div>
        )}
      </Modal>
    </div>
  );
}
